# Generated by Django 3.2.7 on 2021-10-05 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_organized_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organized_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.club'),
        ),
    ]
