# Generated by Django 3.2.8 on 2021-10-06 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_organized_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circular',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.department'),
        ),
    ]
