# Generated by Django 3.2.8 on 2021-10-06 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_circular_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circular',
            name='department',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='event.department'),
            preserve_default=False,
        ),
    ]
