# Generated by Django 3.2.8 on 2021-10-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_circular_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circular',
            name='department',
        ),
        migrations.AddField(
            model_name='circular',
            name='department',
            field=models.ManyToManyField(to='event.Department'),
        ),
    ]
