# Generated by Django 3.2.8 on 2021-10-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20211006_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circular',
            name='department',
            field=models.ManyToManyField(related_name='department', to='event.Department'),
        ),
    ]
