# Generated by Django 3.2.7 on 2021-10-07 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_student_reg_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
