# Generated by Django 3.2.7 on 2021-10-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_remove_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
